/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int mpc_step(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int mpc_step_alloc_mem(void);
int mpc_step_init_mem(int mem);
void mpc_step_free_mem(int mem);
int mpc_step_checkout(void);
void mpc_step_release(int mem);
void mpc_step_incref(void);
void mpc_step_decref(void);
casadi_int mpc_step_n_in(void);
casadi_int mpc_step_n_out(void);
casadi_real mpc_step_default_in(casadi_int i);
const char* mpc_step_name_in(casadi_int i);
const char* mpc_step_name_out(casadi_int i);
const casadi_int* mpc_step_sparsity_in(casadi_int i);
const casadi_int* mpc_step_sparsity_out(casadi_int i);
int mpc_step_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#ifdef __cplusplus
} /* extern "C" */
#endif
